<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '';
echo '<title>Users Profile</title>';
echo '<meta content="" name="description">';
echo '<meta content="" name="keywords">';
echo '';
echo '';
echo '<link href="assets/img/favicon.png" rel="icon">';
echo '<link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">';
echo '';
echo '';
echo '<link href="https://fonts.gstatic.com" rel="preconnect">';
echo '<link';
echo 'href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"';
echo 'rel="stylesheet">';
echo '';
echo '';
echo '<link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">';
echo '<link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">';
echo '<link href="assets/vendor/quill/quill.snow.css" rel="stylesheet">';
echo '<link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet">';
echo '<link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">';
echo '<link href="assets/vendor/simple-datatables/style.css" rel="stylesheet">';
echo '';
echo '';
echo '<link href="assets/css/style.css" rel="stylesheet">';
echo '';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<!-- ======= Header ======= -->';
echo '<header id="header" class="header fixed-top d-flex align-items-center">';
echo '';
echo '<div class="d-flex align-items-center justify-content-between">';
echo '<a href="index.html" class="logo d-flex align-items-center">';
echo '</a>';
echo '</div><!-- End Logo -->';
echo '';
echo '<div class="search-bar">';
echo '<form class="search-form d-flex align-items-center" method="POST" action="#">';
echo '<input type="text" name="query" placeholder="Search" title="Enter search keyword">';
echo '<button type="submit" title="Search"><i class="bi bi-search"></i></button>';
echo '</form>';
echo '</div><!-- End Search Bar -->';
echo '';
echo '<nav class="header-nav ms-auto">';
echo '<ul class="d-flex align-items-center">';
echo '';
echo '<li class="nav-item d-block d-lg-none">';
echo '<a class="nav-link nav-icon search-bar-toggle " href="#">';
echo '<i class="bi bi-search"></i>';
echo '</a>';
echo '</li><!-- End Search Icon-->';
echo '';
echo '<li class="nav-item dropdown">';
echo '';
echo '<a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">';
echo '<i class="bi bi-bell"></i>';
echo '<span class="badge bg-primary badge-number">4</span>';
echo '</a><!-- End Notification Icon -->';
echo '';
echo '<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">';
echo '<li class="dropdown-header">';
echo 'You have 4 new notifications';
echo '<a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li class="notification-item">';
echo '<i class="bi bi-exclamation-circle text-warning"></i>';
echo '<div>';
echo '<h4>Lorem Ipsum</h4>';
echo '<p>Quae dolorem earum veritatis oditseno</p>';
echo '<p>30 min. ago</p>';
echo '</div>';
echo '</li>';
echo '';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li class="notification-item">';
echo '<i class="bi bi-x-circle text-danger"></i>';
echo '<div>';
echo '<h4>Atque rerum nesciunt</h4>';
echo '<p>Quae dolorem earum veritatis oditseno</p>';
echo '<p>1 hr. ago</p>';
echo '</div>';
echo '</li>';
echo '';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li class="notification-item">';
echo '<i class="bi bi-check-circle text-success"></i>';
echo '<div>';
echo '<h4>Sit rerum fuga</h4>';
echo '<p>Quae dolorem earum veritatis oditseno</p>';
echo '<p>2 hrs. ago</p>';
echo '</div>';
echo '</li>';
echo '';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li class="notification-item">';
echo '<i class="bi bi-info-circle text-primary"></i>';
echo '<div>';
echo '<h4>Dicta reprehenderit</h4>';
echo '<p>Quae dolorem earum veritatis oditseno</p>';
echo '<p>4 hrs. ago</p>';
echo '</div>';
echo '</li>';
echo '';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '<li class="dropdown-footer">';
echo '<a href="#">Show all notifications</a>';
echo '</li>';
echo '';
echo '</ul><!-- End Notification Dropdown Items -->';
echo '';
echo '</li><!-- End Notification Nav -->';
echo '';
echo '<li class="nav-item dropdown">';
echo '';
echo '<a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">';
echo '<i class="bi bi-chat-left-text"></i>';
echo '<span class="badge bg-success badge-number">3</span>';
echo '</a><!-- End Messages Icon -->';
echo '';
echo '<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">';
echo '<li class="dropdown-header">';
echo 'You have 3 new messages';
echo '<a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li class="message-item">';
echo '<a href="#">';
echo '<img src="assets/img/messages-1.jpg" alt="" class="rounded-circle">';
echo '<div>';
echo '<h4>Maria Hudson</h4>';
echo '<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>';
echo '<p>4 hrs. ago</p>';
echo '</div>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li class="message-item">';
echo '<a href="#">';
echo '<img src="assets/img/messages-2.jpg" alt="" class="rounded-circle">';
echo '<div>';
echo '<h4>Anna Nelson</h4>';
echo '<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>';
echo '<p>6 hrs. ago</p>';
echo '</div>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li class="message-item">';
echo '<a href="#">';
echo '<img src="assets/img/messages-3.jpg" alt="" class="rounded-circle">';
echo '<div>';
echo '<h4>David Muldon</h4>';
echo '<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>';
echo '<p>8 hrs. ago</p>';
echo '</div>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li class="dropdown-footer">';
echo '<a href="#">Show all messages</a>';
echo '</li>';
echo '';
echo '</ul><!-- End Messages Dropdown Items -->';
echo '';
echo '</li><!-- End Messages Nav -->';
echo '';
echo '<li class="nav-item dropdown pe-3">';
echo '';
echo '<a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">';
echo '<img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">';
echo '<span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>';
echo '</a><!-- End Profile Iamge Icon -->';
echo '';
echo '<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">';
echo '<li class="dropdown-header">';
echo '<h6>Kevin Anderson</h6>';
echo '<span>Provider</span>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li>';
echo '<a class="dropdown-item d-flex align-items-center" href="users-profile.html">';
echo '<i class="bi bi-person"></i>';
echo '<span>My Profile</span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li>';
echo '<a class="dropdown-item d-flex align-items-center" href="users-profile.html">';
echo '<i class="bi bi-gear"></i>';
echo '<span>Account Settings</span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li>';
echo '<a class="dropdown-item d-flex align-items-center" href="pages-faq.html">';
echo '<i class="bi bi-question-circle"></i>';
echo '<span>Need Help?</span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<hr class="dropdown-divider">';
echo '</li>';
echo '';
echo '<li>';
echo '<a class="dropdown-item d-flex align-items-center" href="#">';
echo '<i class="bi bi-box-arrow-right"></i>';
echo '<span>Sign Out</span>';
echo '</a>';
echo '</li>';
echo '';
echo '</ul><!-- End Profile Dropdown Items -->';
echo '</li><!-- End Profile Nav -->';
echo '';
echo '</ul>';
echo '</nav><!-- End Icons Navigation -->';
echo '';
echo '</header><!-- End Header -->';
echo '';
echo '<main id="main" class="main">';
echo '';
echo '<div class="pagetitle">';
echo '<h1>Profile</h1>';
echo '<nav>';
echo '<ol class="breadcrumb">';
echo '<li class="breadcrumb-item"><a href="index.html">Home</a></li>';
echo '<li class="breadcrumb-item">Users</li>';
echo '<li class="breadcrumb-item active">Profile</li>';
echo '</ol>';
echo '</nav>';
echo '</div><!-- End Page Title -->';
echo '';
echo '<section class="section profile">';
echo '<div class="row">';
echo '<div class="col-xl-4">';
echo '';
echo '<div class="card">';
echo '<div class="card-body profile-card pt-4 d-flex flex-column align-items-center">';
echo '';
echo '<img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">';
echo '<h2>Kevin Anderson</h2>';
echo '<h3>Provider</h3>';
echo '<div class="social-links mt-2">';
echo '<a href="#" class="twitter"><i class="bi bi-twitter"></i></a>';
echo '<a href="#" class="facebook"><i class="bi bi-facebook"></i></a>';
echo '<a href="#" class="instagram"><i class="bi bi-instagram"></i></a>';
echo '<a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="col-xl-8">';
echo '';
echo '<div class="card">';
echo '<div class="card-body pt-3">';
echo '<!-- Bordered Tabs -->';
echo '<ul class="nav nav-tabs nav-tabs-bordered">';
echo '';
echo '<li class="nav-item">';
echo '<button class="nav-link active" data-bs-toggle="tab"';
echo 'data-bs-target="#profile-overview">Overview</button>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-settings">Settings</button>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change';
echo 'Password</button>';
echo '</li>';
echo '';
echo '</ul>';
echo '<div class="tab-content pt-2">';
echo '';
echo '<div class="tab-pane fade show active profile-overview" id="profile-overview">';
echo '<h5 class="card-title">About</h5>';
echo '<p class="small fst-italic">Sunt est soluta temporibus accusantium neque nam maiores cumque';
echo 'temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem';
echo 'eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</p>';
echo '';
echo '<h5 class="card-title">Profile Details</h5>';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-4 label ">Full Name</div>';
echo '<div class="col-lg-9 col-md-8">Kevin Anderson</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-4 label">Company</div>';
echo '<div class="col-lg-9 col-md-8">Waste Connect</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-4 label">Job</div>';
echo '<div class="col-lg-9 col-md-8">Provider</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-4 label">Country</div>';
echo '<div class="col-lg-9 col-md-8">IND</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-4 label">Address</div>';
echo '<div class="col-lg-9 col-md-8">Lamnyong</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-4 label">Phone</div>';
echo '<div class="col-lg-9 col-md-8">(+62) 123-456-789</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-4 label">Email</div>';
echo '<div class="col-lg-9 col-md-8">kevin@gmail.com</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="tab-pane fade profile-edit pt-3" id="profile-edit">';
echo '';
echo '<!-- Profile Edit Form -->';
echo '<form>';
echo '<div class="row mb-3">';
echo '<label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<img src="assets/img/profile-img.jpg" alt="Profile">';
echo '<div class="pt-2">';
echo '<a href="#" class="btn btn-primary btn-sm" title="Upload new profile image"><i';
echo 'class="bi bi-upload"></i></a>';
echo '<a href="#" class="btn btn-danger btn-sm" title="Remove my profile image"><i';
echo 'class="bi bi-trash"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="fullName" class="col-md-4 col-lg-3 col-form-label">Full Name</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="fullName" type="text" class="form-control" id="fullName" value="Kevin Anderson">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="about" class="col-md-4 col-lg-3 col-form-label">About</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<textarea name="about" class="form-control" id="about"';
echo 'style="height: 100px">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</textarea>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="company" class="col-md-4 col-lg-3 col-form-label">Company</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="company" type="text" class="form-control" id="company" value="Waste Connect">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Job" class="col-md-4 col-lg-3 col-form-label">Job</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="job" type="text" class="form-control" id="Job" value="Provider">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Country" class="col-md-4 col-lg-3 col-form-label">Country</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="country" type="text" class="form-control" id="Country" value="IND">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Address" class="col-md-4 col-lg-3 col-form-label">Address</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="address" type="text" class="form-control" id="Address" value="Lamnyong">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Phone" class="col-md-4 col-lg-3 col-form-label">Phone</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="phone" type="text" class="form-control" id="Phone" value="(+62) 123-456-789">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Email" class="col-md-4 col-lg-3 col-form-label">Email</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="email" type="email" class="form-control" id="Email" value="kevin@gmail.com">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Twitter" class="col-md-4 col-lg-3 col-form-label">Twitter Profile</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="twitter" type="text" class="form-control" id="Twitter"';
echo 'value="https://twitter.com/#">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Facebook" class="col-md-4 col-lg-3 col-form-label">Facebook Profile</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="facebook" type="text" class="form-control" id="Facebook"';
echo 'value="https://facebook.com/#">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Instagram" class="col-md-4 col-lg-3 col-form-label">Instagram Profile</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="instagram" type="text" class="form-control" id="Instagram"';
echo 'value="https://instagram.com/#">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="Linkedin" class="col-md-4 col-lg-3 col-form-label">Linkedin Profile</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="linkedin" type="text" class="form-control" id="Linkedin"';
echo 'value="https://linkedin.com/#">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="text-center">';
echo '<button type="submit" class="btn btn-primary">Save Changes</button>';
echo '</div>';
echo '</form><!-- End Profile Edit Form -->';
echo '';
echo '</div>';
echo '';
echo '<div class="tab-pane fade pt-3" id="profile-settings">';
echo '';
echo '<!-- Settings Form -->';
echo '<form>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<div class="form-check">';
echo '<input class="form-check-input" type="checkbox" id="changesMade" checked>';
echo '<label class="form-check-label" for="changesMade">';
echo 'Changes made to your account';
echo '</label>';
echo '</div>';
echo '<div class="form-check">';
echo '<input class="form-check-input" type="checkbox" id="newProducts" checked>';
echo '<label class="form-check-label" for="newProducts">';
echo 'Information on new products and services';
echo '</label>';
echo '</div>';
echo '<div class="form-check">';
echo '<input class="form-check-input" type="checkbox" id="proOffers">';
echo '<label class="form-check-label" for="proOffers">';
echo 'Marketing and promo offers';
echo '</label>';
echo '</div>';
echo '<div class="form-check">';
echo '<input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>';
echo '<label class="form-check-label" for="securityNotify">';
echo 'Security alerts';
echo '</label>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="text-center">';
echo '<button type="submit" class="btn btn-primary">Save Changes</button>';
echo '</div>';
echo '</form><!-- End settings Form -->';
echo '';
echo '</div>';
echo '';
echo '<div class="tab-pane fade pt-3" id="profile-change-password">';
echo '<!-- Change Password Form -->';
echo '<form>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="password" type="password" class="form-control" id="currentPassword">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="newpassword" type="password" class="form-control" id="newPassword">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row mb-3">';
echo '<label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>';
echo '<div class="col-md-8 col-lg-9">';
echo '<input name="renewpassword" type="password" class="form-control" id="renewPassword">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="text-center">';
echo '<button type="submit" class="btn btn-primary">Change Password</button>';
echo '</div>';
echo '</form><!-- End Change Password Form -->';
echo '';
echo '</div>';
echo '';
echo '</div><!-- End Bordered Tabs -->';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '</main><!-- End #main -->';
echo '';
echo '<!-- ======= Footer ======= -->';
echo '<footer id="footer" class="footer">';
echo '<div class="copyright">';
echo '&copy; Copyright. All Rights Reserved';
echo '</div>';
echo '<div class="credits">';
echo '';
echo '';
echo '</div>';
echo '</footer><!-- End Footer -->';
echo '';
echo '<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i';
echo 'class="bi bi-arrow-up-short"></i></a>';
echo '';
echo '<!-- Vendor JS Files -->';
echo '<script src="assets/vendor/apexcharts/apexcharts.min.js"></script>';
echo '<script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>';
echo '<script src="assets/vendor/chart.js/chart.umd.js"></script>';
echo '<script src="assets/vendor/echarts/echarts.min.js"></script>';
echo '<script src="assets/vendor/quill/quill.min.js"></script>';
echo '<script src="assets/vendor/simple-datatables/simple-datatables.js"></script>';
echo '<script src="assets/vendor/tinymce/tinymce.min.js"></script>';
echo '<script src="assets/vendor/php-email-form/validate.js"></script>';
echo '';
echo '<script src="assets/js/main.js"></script>';
echo '';
echo '</body>';
echo '';
echo '</html>';
?>
